title: Serhat Giydiren
description: me@serhatgiydiren
google_analytics: UA-147444535-1

author:
  name: "Serhat Giydiren"
  email: "serhatgiydiren@gmail.com"
  url: "https://serhatgiydiren.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "me"
year : "2020"

theme: jekyll-theme-hacker
